source 'https://github.com/CocoaPods/Specs.git'

target 'Pathero', :exclusive => true do
  pod "Pathero", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "Pathero", :path => "../"

  pod 'Kiwi'
end
